name: Windows CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: 'stable'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Nim version
        run: nim -v

      - name: Build release binary
        run: nimble build -d:release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fastfind-windows
          path: |
            *.exe
            dist/*.exe