name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: stable

      - name: Build release binary
        run: nim c -d:release --app:console -o:fastfind.exe src/main.nim

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fastfind-windows
          path: fastfind.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: fastfind.exe